---

- name: repository | add public key
  shell: gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E084DAB9;gpg -a --export E084DAB9 | sudo apt-key add -

- name: repository | add cran-r
  apt_repository: repo="deb http://cran.rstudio.com/bin/linux/ubuntu {{ansible_distribution_release}}/" state=present update_cache=true

- name: install r and devtools's dependencies
  apt: name={{ item }} state=present
  with_items:
    - r-recommended
    - libcurl4-gnutls-dev
    - libxml2-dev
    - libssl-dev

- name: install IRkernel's dependencies
  command: R --quiet -e "if (! '{{item}}' %in% installed.packages()[,'Package']) install.packages('{{item}}', repos='http://cran.rstudio.com/')"
  with_items:
    - repr
    - IRdisplay
    - evaluate
    - crayon
    - pbdZMQ
    - devtools
    - uuid
    - digest
    - stringi

- name: install IRkernel
  command: R --quiet -e "if (! '{{item}}' %in% installed.packages()[,'Package']) devtools::install_github('IRkernel/{{item}}')"
  with_items:
    - IRkernel

- name: install irkernel kernelspec for jupyter
  command: R --quiet -e "IRkernel::installspec(user = FALSE)"

- name: install additional R packages
  command: R --quiet -e "if (! '{{item}}' %in% installed.packages()[,'Package']) install.packages('{{item}}', repos='http://cran.rstudio.com/')"
  with_items: '{{cran_packages}}'
